language: python
python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7-dev
before_script: # make build not fail on travisci when working with boto and moto... https://github.com/spulec/moto/issues/1771
  - export BOTO_CONFIG=/dev/null
  - export AWS_SECRET_ACCESS_KEY=foobar_secret
  - export AWS_ACCESS_KEY_ID=foobar_key
install: ./go setup
script: ./go check && ./go test
addons:
  apt:
    packages:
    - pandoc