language: python
python:
  - 3.4
  - 3.5
  - 3.6

# 3.7 workaround according to this: https://github.com/travis-ci/travis-ci/issues/9815#issue-336465122
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install: ./go setup
script: ./go check && ./go test
addons:
  apt:
    packages:
    - pandoc