#!/usr/bin/python3.8
# -*- coding: utf-8 -*-
import re
import sys
from trailscraper.cli import root_group
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(root_group())
